CREATE TABLE USER_PROFILE(
    ID VARCHAR PRIMARY KEY NOT NULL,
    NAME VARCHAR NOT NULL,
    USER_NAME VARCHAR NOT NULL,
    BIO VARCHAR,
    -- URL
    AVATAR VARCHAR,
    -- DATE
    LAST_SEEN TEXT,
    -- DATE
    LAST_MODIFIED TEXT,

    FOREIGN KEY(ID) REFERENCES USER(ID)
);
