CREATE TABLE USER(
    ID VARCHAR PRIMARY KEY NOT NULL,
    PUBKEY VARCHAR NOT NULL
);

CREATE TABLE USER_PROFILE(
    ID VARCHAR PRIMARY KEY NOT NULL,
    NAME VARCHAR NOT NULL,
    USER_NAME VARCHAR NOT NULL,
    BIO VARCHAR,
    -- URL
    AVATAR VARCHAR,
    -- DATE
    LAST_SEEN TEXT,
    -- DATE
    LAST_MODIFIED TEXT,

    FOREIGN KEY(ID) REFERENCES USER(ID)
);

CREATE TABLE USER_PRIVACY_SETTINGS(
    ID VARCHAR PRIMARY KEY NOT NULL,
    -- VISIBILITY
    AVATAR VARCHAR NOT NULL,
    -- VISIBILITY
    LAST_SEEN VARCHAR NOT NULL,
    -- VISIBILITY
    JOINED_GROUPS VARCHAR NOT NULL,
    -- VISIBILITY
    FORWARDS VARCHAR NOT NULL,
    -- DURATION
    JWT_EXPIRATION VARCHAR NOT NULL,

    FOREIGN KEY(ID) REFERENCES USER(ID)
);
