CREATE TABLE MESSAGE(
    EVENT_ID VARCHAR PRIMARY KEY NOT NULL,
    RECEIVER_ID VARCHAR NOT NULL,
    RECEIVER_SERVER VARCHAR NOT NULL,
    TEXT VARCHAR NOT NULL,
    -- SERIALIZED JSON
    EXTENSIONS VARCHAR NOT NULL,
    
    FOREIGN KEY(EVENT_ID) REFERENCES EVENT(ID)
);
