CREATE TABLE MESSAGE (
    ID VARCHAR PRIMARY KEY NOT NULL,
    TS BIGINT NOT NULL,
    SENDER VARCHAR NOT NULL,
    RECEIVER_ID VARCHAR NOT NULL,
    RECEIVER_SERVER VARCHAR NOT NULL,
    TEXT VARCHAR NOT NULL,
    -- SERIALIZED JSON
    EXTENSIONS VARCHAR NOT NULL
);
